source 'https://rubygems.org'
gem 'rails', '4.2.0'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'backbone-on-rails'
gem 'bcrypt'
gem 'bootstrap-sass'
gem 'jquery-ui-rails'
gem 'newrelic_rpm'
gem "paperclip", "~> 4.2"
gem 'aws-sdk', '<2.0'
gem 'figaro'
gem 'gravtastic'
group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry-rails'
  gem 'faker'
end
